version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.7  # Use a Docker image with SSH tools installed
    steps:
      - checkout  # Check out the repository

      # 1. Add EC2 instance to known_hosts to avoid authenticity prompts
      - run:
          name: Add EC2 to Known Hosts
          command: |
            ssh-keyscan -H 100.27.229.255 >> ~/.ssh/known_hosts

      # 2. Deploy HTML files and folders to the EC2 instance
      - run:
          name: Deploy HTML Files
          command: |
            pwd
            ls
            scp -r ./* ubuntu@100.27.229.255:/var/www/html/
            ssh ubuntu@100.27.229.255 'sudo systemctl restart nginx'  # Restart web server if necessary

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy
