version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/python:3.8.4  # Use a docker image with SSH tools installed
    steps:
      - checkout  # Check out the repository

      # 1. Create SSH directory
      - run:
          name: Create SSH Directory
          command: mkdir -p ~/.ssh

      # 2. Add SSH Private Key from the environment variables
      - run:
          name: Add SSH Private Key
          command: |
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa

      # 3. Add the known_hosts to prevent host verification issues
      - run:
          name: Add EC2 to Known Hosts
          command: |
            ssh-keyscan -H 100.27.229.255 >> ~/.ssh/known_hosts

      # 4. Deploy the application to EC2
      - run:
          name: Deploy to EC2
          command: |
            pwd
            ls
            scp -r ./* ubuntu@100.27.229.255:/var/www/html/
            ssh ubuntu@100.27.229.255 'sudo systemctl restart apache2'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy
